name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version you are using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run flake8 (Linting)
      run: |
        flake8 my_package tests

    - name: Run black (Formatting)
      run: |
        black --check my_package tests

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings  # Stop after first failure, disable warnings for cleaner output